### ISSUE TITLE
Ability to set global defaults for Title, meta content, meta description, and meta keyword tags

### ISSUE THREAD

**Issue by juampynr** [Lullabot/metatag#1]

**Comment by juampynr** [comment]
I will start by implementing this simple UI for the global metatags:

![image](https://cloud.githubusercontent.com/assets/108130/11207927/8153cdee-8d18-11e5-955b-009656e6260a.png)

**Comment by juampynr** [comment]
@davereid, shall we implement all the options that are available in the Drupal 7 module? This is what comes by default:

![image](https://cloud.githubusercontent.com/assets/108130/11271690/ff6934e8-8ec7-11e5-9413-dd056895dfc2.png)

**Comment by davereid** [comment]
@juampy72 I think we can just start with page title, description, keywords, and robots for now.

**Comment by juampynr** [comment]
:+1:

**Comment by juampynr** [comment]
Pull request https://github.com/Lullabot/metatag/pull/8 implements tags as plugins.

**Comment by juampynr** [comment]
Pull request https://github.com/Lullabot/metatag/pull/10 moves tag rendering to its plugins.
